import json
import os

cells = [
    # CELL 0: Title
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 🚀 SPEC-03 (Local CUDA GPU Edition)\n",
            "## 📌 XLM-RoBERTa Aspect-Based Sentiment Analysis Classifier\n",
            "\n",
            "Notebook ini dikhususkan untuk **pelatihan lokal** model **XLM-RoBERTa** menggunakan **GPU NVIDIA CUDA** (misalnya RTX 3050 Laptop / RTX 3060 / VRAM 4GB+).\n",
            "\n",
            "### 🎯 Fitur & Optimasi Utama Versi Lokal:\n",
            "1. **Model Tunggal Focused Target:** Khusus melatih **XLM-RoBERTa** (`xlm-roberta-base` atau `xlm-roberta-large`).\n",
            "2. **Optimasi VRAM (Automatic Mixed Precision FP16):** Menggunakan `torch.cuda.amp.autocast()` dan `GradScaler()` agar hemat VRAM GPU lokal serta 2x lebih cepat.\n",
            "3. **Partial Fine-Tuning Option:** Mendukung pembekuan (*freezing*) layer awal encoder untuk mempercepat pelatihan dan mencegah over-fitting pada GPU lokal.\n",
            "4. **Single Best Model Disk Safeguard:** Hanya menyimpan **1 file model terbaik** (`models/xlmroberta_absa/pytorch_model.bin`) dari seluruh fold untuk menghemat ruang penyimpanan SSD lokal.\n",
            "5. **Real-Time Epoch Logging:** Menampilkan *Train Loss*, *Val F1 (Active Sentiments)*, *Val F1 (All Classes)*, dan *Val Accuracy* di setiap epoch.\n",
            "6. **Aspect-Customized Thresholding (${\\theta}_{\\text{aspect}}$):** `purnajual`: 0.35, `infra`: 0.40, `ekonomi`: 0.50, `kualitas`: 0.50.\n"
        ]
    },
    # CELL 1: Section 1 Markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 1. Setup Dependencies, CUDA GPU Check & Constants\n"
        ]
    },
    # CELL 2: Section 1 Code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import gc\n",
            "import json\n",
            "import zipfile\n",
            "from pathlib import Path\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "from tqdm.auto import tqdm\n",
            "\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "import torch.nn.functional as F\n",
            "from torch.utils.data import Dataset, DataLoader\n",
            "from transformers import get_cosine_schedule_with_warmup, AutoModel, AutoTokenizer\n",
            "from sklearn.model_selection import StratifiedKFold\n",
            "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix\n",
            "from sklearn.utils.class_weight import compute_class_weight\n",
            "\n",
            "# Check CUDA GPU availability\n",
            "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
            "print(f\"⚡ Device Utama: {device}\")\n",
            "if torch.cuda.is_available():\n",
            "    print(f\"🎮 GPU Name: {torch.cuda.get_device_name(0)}\")\n",
            "    print(f\"💾 Total VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB\")\n",
            "    print(f\"🚀 CUDA Capability: {torch.cuda.get_device_capability(0)}\")\n",
            "else:\n",
            "    print(\"⚠️ GPU CUDA tidak terdeteksi. Pelatihan akan menggunakan CPU.\")\n",
            "\n",
            "# Set Random Seed for Reproducibility\n",
            "SEED = 42\n",
            "torch.manual_seed(SEED)\n",
            "np.random.seed(SEED)\n",
            "if torch.cuda.is_available():\n",
            "    torch.cuda.manual_seed_all(SEED)\n",
            "\n",
            "LABEL2ID = {'None': 0, 'none': 0, 'positif': 1, 'netral': 2, 'negatif': 3}\n",
            "ID2LABEL = {0: 'None', 1: 'positif', 2: 'netral', 3: 'negatif'}\n",
            "ASPECTS = ['infra', 'ekonomi', 'kualitas', 'purnajual']\n",
            "CLASS_NAMES = ['None', 'Positif', 'Netral', 'Negatif']\n",
            "\n",
            "# Aspect-customized decision thresholds\n",
            "ASPECT_THRESHOLDS = {\n",
            "    \"infra\": 0.40,\n",
            "    \"ekonomi\": 0.50,\n",
            "    \"kualitas\": 0.50,\n",
            "    \"purnajual\": 0.35,\n",
            "}\n"
        ]
    },
    # CELL 3: Section 2 Markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 2. Load Local Pure Human Gold Standard Dataset\n"
        ]
    },
    # CELL 4: Section 2 Code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Search for local dataset files\n",
            "possible_paths = [\n",
            "    Path(\"data/interim/valid_labeled_comments.csv\"),\n",
            "    Path(\"../data/interim/valid_labeled_comments.csv\"),\n",
            "    Path(\"data/processed/train.csv\"),\n",
            "    Path(\"../data/processed/train.csv\")\n",
            "]\n",
            "\n",
            "full_df = None\n",
            "for p in possible_paths:\n",
            "    if p.exists():\n",
            "        if p.name == \"valid_labeled_comments.csv\":\n",
            "            full_df = pd.read_csv(p, encoding=\"utf-8-sig\")\n",
            "            print(f\"✅ Memuat dataset dari: {p.resolve()}\")\n",
            "            break\n",
            "        elif p.name == \"train.csv\":\n",
            "            val_p = p.parent / \"val.csv\"\n",
            "            if val_p.exists():\n",
            "                df_tr = pd.read_csv(p, encoding=\"utf-8-sig\")\n",
            "                df_va = pd.read_csv(val_p, encoding=\"utf-8-sig\")\n",
            "                full_df = pd.concat([df_tr, df_va], ignore_index=True)\n",
            "                print(f\"✅ Memuat dataset dari gabungan {p.name} & {val_p.name}\")\n",
            "                break\n",
            "\n",
            "if full_df is None:\n",
            "    raise FileNotFoundError(\"❌ Berkas dataset 'valid_labeled_comments.csv' tidak ditemukan! Pastikan Anda berada di direktori proyek.\")\n",
            "\n",
            "print(f\"📊 Total Pure Human Gold Standard Dataset: {len(full_df)} baris\")\n",
            "\n",
            "# Create Stratification Key for Multi-Aspect Stratified K-Fold\n",
            "aspect_cols = [f\"{a}_sentiment\" for a in ASPECTS]\n",
            "full_df['strat_key'] = (\n",
            "    full_df[aspect_cols[0]].fillna('none').astype(str) + '_'\t+\n",
            "    full_df[aspect_cols[1]].fillna('none').astype(str) + '_'\t+\n",
            "    full_df[aspect_cols[2]].fillna('none').astype(str) + '_'\t+\n",
            "    full_df[aspect_cols[3]].fillna('none').astype(str)\n",
            ")\n",
            "\n",
            "counts = full_df['strat_key'].value_counts()\n",
            "rare_keys = set(counts[counts < 5].index)\n",
            "full_df['strat_label'] = full_df['strat_key'].apply(lambda x: 'rare_comb' if x in rare_keys else x)\n",
            "\n",
            "display(full_df.head(3))\n"
        ]
    },
    # CELL 5: Section 3 Markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 3. Loss Function (Focal Loss), Class Weights & ABSADataset\n"
        ]
    },
    # CELL 6: Section 3 Code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "class FocalLoss(nn.Module):\n",
            "    def __init__(self, alpha=None, gamma=1.5):\n",
            "        super().__init__()\n",
            "        self.alpha = alpha\n",
            "        self.gamma = gamma\n",
            "\n",
            "    def forward(self, inputs, targets):\n",
            "        probs = F.softmax(inputs, dim=-1)\n",
            "        pt = probs.gather(1, targets.unsqueeze(1)).squeeze(1)\n",
            "        pt = torch.clamp(pt, min=1e-8, max=1.0)\n",
            "        \n",
            "        focal_weight = (1.0 - pt) ** self.gamma\n",
            "        if self.alpha is not None:\n",
            "            alpha_weight = self.alpha.to(inputs.device)[targets]\n",
            "            focal_weight = focal_weight * alpha_weight\n",
            "\n",
            "        loss = -focal_weight * torch.log(pt)\n",
            "        return loss.mean()\n",
            "\n",
            "def compute_aspect_class_weights(df, aspects=ASPECTS, smooth_factor=0.5):\n",
            "    weights_dict = {}\n",
            "    classes = np.array([0, 1, 2, 3])\n",
            "    for aspect in aspects:\n",
            "        col = f\"{aspect}_sentiment\"\n",
            "        raw_vals = df[col].fillna(\"none\").astype(str).str.lower().map(LABEL2ID).fillna(0).astype(int).values\n",
            "        raw_weights = compute_class_weight(class_weight=\"balanced\", classes=classes, y=raw_vals)\n",
            "        smoothed = np.power(raw_weights, smooth_factor)\n",
            "        smoothed = smoothed / np.mean(smoothed)\n",
            "        weights_dict[aspect] = torch.tensor(smoothed, dtype=torch.float32).to(device)\n",
            "    return weights_dict\n",
            "\n",
            "class ABSADataset(Dataset):\n",
            "    def __init__(self, df, tokenizer, max_len=128, aspects=ASPECTS):\n",
            "        if \"text_cleaned\" in df.columns:\n",
            "            text_col = \"text_cleaned\"\n",
            "        elif \"text_original\" in df.columns:\n",
            "            text_col = \"text_original\"\n",
            "        else:\n",
            "            raise KeyError(f\"❌ Tidak dapat menemukan kolom teks di DataFrame.\")\n",
            "\n",
            "        self.texts = df[text_col].fillna(\"\").astype(str).tolist()\n",
            "        self.labels = {}\n",
            "        for aspect in aspects:\n",
            "            col = f\"{aspect}_sentiment\"\n",
            "            raw = df[col].fillna(\"none\").astype(str).str.lower().map(LABEL2ID).fillna(0).astype(int).values\n",
            "            self.labels[aspect] = torch.tensor(raw, dtype=torch.long)\n",
            "        \n",
            "        self.tokenizer = tokenizer\n",
            "        self.max_len = max_len\n",
            "        self.aspects = aspects\n",
            "\n",
            "    def __len__(self):\n",
            "        return len(self.texts)\n",
            "\n",
            "    def __getitem__(self, idx):\n",
            "        text = self.texts[idx]\n",
            "        encoding = self.tokenizer(\n",
            "            text,\n",
            "            truncation=True,\n",
            "            max_length=self.max_len,\n",
            "            padding=\"max_length\",\n",
            "            return_tensors=\"pt\"\n",
            "        )\n",
            "        \n",
            "        item = {\n",
            "            \"input_ids\": encoding[\"input_ids\"].squeeze(0),\n",
            "            \"attention_mask\": encoding[\"attention_mask\"].squeeze(0),\n",
            "            \"labels\": {aspect: self.labels[aspect][idx] for aspect in self.aspects}\n",
            "        }\n",
            "        return item\n"
        ]
    },
    # CELL 7: Section 4 Markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 4. Model Architecture: XLM-RoBERTa Multi-Head Classifier\n"
        ]
    },
    # CELL 8: Section 4 Code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "class XLMRoBERTaMultiHeadClassifier(nn.Module):\n",
            "    def __init__(self, model_name=\"xlm-roberta-base\", num_classes=4, dropout_prob=0.1, aspects=ASPECTS, focal_gamma=1.5, unfreeze_last_n_layers=None):\n",
            "        super().__init__()\n",
            "        self.aspects = aspects\n",
            "        self.focal_gamma = focal_gamma\n",
            "        self.encoder = AutoModel.from_pretrained(model_name)\n",
            "        hidden_size = self.encoder.config.hidden_size\n",
            "\n",
            "        # Optional Partial Fine-Tuning: Unfreeze only top N encoder layers\n",
            "        if unfreeze_last_n_layers is not None:\n",
            "            print(f\"🔒 Partial Fine-Tuning Active: Unfreezing top {unfreeze_last_n_layers} layers of encoder...\")\n",
            "            for param in self.encoder.parameters():\n",
            "                param.requires_grad = False\n",
            "            # Unfreeze embeddings & top encoder layers\n",
            "            if hasattr(self.encoder, \"encoder\") and hasattr(self.encoder.encoder, \"layer\"):\n",
            "                num_layers = len(self.encoder.encoder.layer)\n",
            "                for layer in self.encoder.encoder.layer[max(0, num_layers - unfreeze_last_n_layers):]:\n",
            "                    for param in layer.parameters():\n",
            "                        param.requires_grad = True\n",
            "\n",
            "        # Expanded 2-Layer GELU MLP Head with LayerNorm (2*hidden_size -> 512 -> 4)\n",
            "        self.heads = nn.ModuleDict({\n",
            "            aspect: nn.Sequential(\n",
            "                nn.Linear(hidden_size * 2, 512),\n",
            "                nn.LayerNorm(512),\n",
            "                nn.GELU(),\n",
            "                nn.Dropout(dropout_prob),\n",
            "                nn.Linear(512, num_classes)\n",
            "            ) for aspect in aspects\n",
            "        })\n",
            "\n",
            "    def forward(self, input_ids, attention_mask, labels=None, class_weights=None):\n",
            "        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)\n",
            "        last_hidden = outputs.last_hidden_state\n",
            "\n",
            "        cls_token = last_hidden[:, 0, :]\n",
            "        input_mask_expanded = attention_mask.unsqueeze(-1).expand(last_hidden.size()).float()\n",
            "        sum_embeddings = torch.sum(last_hidden * input_mask_expanded, dim=1)\n",
            "        sum_mask = torch.clamp(input_mask_expanded.sum(dim=1), min=1e-9)\n",
            "        mean_pooled = sum_embeddings / sum_mask\n",
            "\n",
            "        pooled_features = torch.cat([cls_token, mean_pooled], dim=-1)\n",
            "\n",
            "        logits = {}\n",
            "        total_loss = 0.0\n",
            "\n",
            "        for aspect in self.aspects:\n",
            "            aspect_logits = self.heads[aspect](pooled_features)\n",
            "            logits[aspect] = aspect_logits\n",
            "\n",
            "            if labels is not None:\n",
            "                target = labels[aspect].to(aspect_logits.device)\n",
            "                alpha = class_weights[aspect] if class_weights and aspect in class_weights else None\n",
            "                criterion = FocalLoss(alpha=alpha, gamma=self.focal_gamma)\n",
            "                total_loss += criterion(aspect_logits, target)\n",
            "\n",
            "        output_dict = {\"logits\": logits}\n",
            "        if labels is not None:\n",
            "            output_dict[\"loss\"] = total_loss\n",
            "        return output_dict\n"
        ]
    },
    # CELL 9: Section 5 Markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 5. Thresholding & Evaluation Helper Functions\n"
        ]
    },
    # CELL 10: Section 5 Code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def predict_with_threshold(logits, none_threshold=ASPECT_THRESHOLDS, aspect=None):\n",
            "    if isinstance(none_threshold, dict) and aspect in none_threshold:\n",
            "        thresh = none_threshold[aspect]\n",
            "    elif isinstance(none_threshold, (int, float)):\n",
            "        thresh = float(none_threshold)\n",
            "    else:\n",
            "        thresh = 0.50\n",
            "\n",
            "    if isinstance(logits, torch.Tensor):\n",
            "        probs = F.softmax(logits, dim=-1).detach().cpu().numpy()\n",
            "    else:\n",
            "        exp_logits = np.exp(logits - np.max(logits, axis=-1, keepdims=True))\n",
            "        probs = exp_logits / np.sum(exp_logits, axis=-1, keepdims=True)\n",
            "\n",
            "    preds = []\n",
            "    for i in range(probs.shape[0]):\n",
            "        p_none = probs[i, 0]\n",
            "        if p_none > thresh:\n",
            "            preds.append(0)\n",
            "        else:\n",
            "            active_probs = probs[i, 1:]\n",
            "            best_active_idx = int(np.argmax(active_probs)) + 1\n",
            "            preds.append(best_active_idx)\n",
            "\n",
            "    return np.array(preds)\n",
            "\n",
            "def evaluate_predictions(y_true_dict, y_pred_dict, aspects=ASPECTS):\n",
            "    aspect_metrics = {}\n",
            "    cm_dict = {}\n",
            "    macro_f1s_all, macro_f1s_active, accuracies = [], [], []\n",
            "\n",
            "    for aspect in aspects:\n",
            "        y_true = np.array(y_true_dict[aspect])\n",
            "        y_pred = np.array(y_pred_dict[aspect])\n",
            "\n",
            "        acc = accuracy_score(y_true, y_pred)\n",
            "        f1_m_all = f1_score(y_true, y_pred, average=\"macro\", zero_division=0)\n",
            "        f1_m_active = f1_score(y_true, y_pred, labels=[1, 2, 3], average=\"macro\", zero_division=0)\n",
            "\n",
            "        prec_m = precision_score(y_true, y_pred, average=\"macro\", zero_division=0)\n",
            "        rec_m = recall_score(y_true, y_pred, average=\"macro\", zero_division=0)\n",
            "        f1_w = f1_score(y_true, y_pred, average=\"weighted\", zero_division=0)\n",
            "\n",
            "        cm = confusion_matrix(y_true, y_pred, labels=[0, 1, 2, 3])\n",
            "\n",
            "        aspect_metrics[aspect] = {\n",
            "            \"accuracy\": acc,\n",
            "            \"f1_macro_all\": f1_m_all,\n",
            "            \"f1_macro_active\": f1_m_active,\n",
            "            \"precision_macro\": prec_m,\n",
            "            \"recall_macro\": rec_m,\n",
            "            \"f1_weighted\": f1_w,\n",
            "        }\n",
            "        cm_dict[aspect] = cm\n",
            "        accuracies.append(acc)\n",
            "        macro_f1s_all.append(f1_m_all)\n",
            "        macro_f1s_active.append(f1_m_active)\n",
            "\n",
            "    n_samples = len(y_true_dict[aspects[0]])\n",
            "    exact_matches = sum(\n",
            "        all(y_true_dict[asp][i] == y_pred_dict[asp][i] for asp in aspects)\n",
            "        for i in range(n_samples)\n",
            "    )\n",
            "    exact_match_ratio = exact_matches / n_samples if n_samples > 0 else 0.0\n",
            "\n",
            "    return {\n",
            "        \"per_aspect\": aspect_metrics,\n",
            "        \"overall\": {\n",
            "            \"mean_accuracy\": float(np.mean(accuracies)),\n",
            "            \"mean_macro_f1_all\": float(np.mean(macro_f1s_all)),\n",
            "            \"mean_macro_f1_active\": float(np.mean(macro_f1s_active)),\n",
            "            \"exact_match_ratio\": float(exact_match_ratio),\n",
            "        },\n",
            "        \"confusion_matrices\": cm_dict,\n",
            "    }\n",
            "\n",
            "def plot_confusion_matrices(cm_dict, model_name, save_path, aspects=ASPECTS):\n",
            "    fig, axes = plt.subplots(2, 2, figsize=(12, 10))\n",
            "    fig.suptitle(f\"Confusion Matrices 4x4 — {model_name}\", fontsize=16, fontweight=\"bold\", y=0.98)\n",
            "\n",
            "    for idx, aspect in enumerate(aspects):\n",
            "        ax = axes[idx // 2, idx % 2]\n",
            "        cm = cm_dict[aspect]\n",
            "        sns.heatmap(cm, annot=True, fmt=\"d\", cmap=\"Blues\", cbar=False, ax=ax,\n",
            "                    xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES)\n",
            "        ax.set_title(f\"Aspek: {aspect.capitalize()}\", fontsize=14, fontweight=\"semibold\")\n",
            "        ax.set_xlabel(\"Predicted Label\", fontsize=11)\n",
            "        ax.set_ylabel(\"True Label\", fontsize=11)\n",
            "\n",
            "    plt.tight_layout(rect=[0, 0, 1, 0.95])\n",
            "    plt.savefig(save_path, dpi=300, bbox_inches=\"tight\")\n",
            "    plt.show()\n",
            "    plt.close()\n",
            "    return save_path\n"
        ]
    },
    # CELL 11: Section 6 Markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 6. Local 5-Fold Stratified Cross-Validation Training Loop (FP16 AMP Optimized)\n"
        ]
    },
    # CELL 12: Section 6 Code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def train_5fold_cv_local(\n",
            "    model_name=\"xlm-roberta-base\",\n",
            "    tokenizer=None,\n",
            "    full_df=None,\n",
            "    epochs=20,\n",
            "    lr=2e-5,\n",
            "    batch_size=16,\n",
            "    grad_accum=1,\n",
            "    save_prefix=\"xlmroberta_local_absa\",\n",
            "    unfreeze_last_n_layers=None\n",
            "):\n",
            "    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)\n",
            "    fold_metrics = []\n",
            "    save_dir = Path(f\"models/{save_prefix}\")\n",
            "    save_dir.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "    best_overall_val_f1 = 0.0\n",
            "    best_model_path = save_dir / \"pytorch_model.bin\"\n",
            "\n",
            "    print(f\"\\n🚀 MEMULAI 5-FOLD CROSS-VALIDATION LOKAL: {model_name}\")\n",
            "    print(f\"⚙️ Config: Epochs={epochs}, LR={lr}, BatchSize={batch_size}, GradAccum={grad_accum}, AMP FP16=True\")\n",
            "    print(f\"💾 Disk Safeguard: Hanya menyimpan 1 Single Best Model Checkpoint ({best_model_path.resolve()})\")\n",
            "\n",
            "    # PyTorch Automatic Mixed Precision (AMP) Scaler\n",
            "    scaler = torch.cuda.amp.GradScaler(enabled=torch.cuda.is_available())\n",
            "\n",
            "    for fold, (train_idx, val_idx) in enumerate(skf.split(full_df, full_df['strat_label']), 1):\n",
            "        print(f\"\\n========================================================\")\n",
            "        print(f\"🔄 FOLD {fold}/5 — {model_name}\")\n",
            "        print(f\"========================================================\")\n",
            "\n",
            "        train_fold_df = full_df.iloc[train_idx].reset_index(drop=True)\n",
            "        val_fold_df = full_df.iloc[val_idx].reset_index(drop=True)\n",
            "\n",
            "        class_weights = compute_aspect_class_weights(train_fold_df)\n",
            "\n",
            "        train_dataset = ABSADataset(train_fold_df, tokenizer, max_len=128)\n",
            "        val_dataset = ABSADataset(val_fold_df, tokenizer, max_len=128)\n",
            "\n",
            "        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)\n",
            "        val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)\n",
            "\n",
            "        model = XLMRoBERTaMultiHeadClassifier(model_name, unfreeze_last_n_layers=unfreeze_last_n_layers).to(device)\n",
            "\n",
            "        total_steps = (len(train_loader) // grad_accum) * epochs\n",
            "        optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad, model.parameters()), lr=lr, weight_decay=0.01)\n",
            "        scheduler = get_cosine_schedule_with_warmup(\n",
            "            optimizer,\n",
            "            num_warmup_steps=int(0.1 * total_steps),\n",
            "            num_training_steps=max(1, total_steps)\n",
            "        )\n",
            "\n",
            "        best_fold_f1_active = 0.0\n",
            "        best_fold_eval = None\n",
            "\n",
            "        for epoch in range(1, epochs + 1):\n",
            "            model.train()\n",
            "            total_train_loss = 0.0\n",
            "            optimizer.zero_grad()\n",
            "\n",
            "            for step, batch in enumerate(train_loader):\n",
            "                input_ids = batch[\"input_ids\"].to(device)\n",
            "                attention_mask = batch[\"attention_mask\"].to(device)\n",
            "                labels = {k: v.to(device) for k, v in batch[\"labels\"].items()}\n",
            "\n",
            "                # FP16 Autocast for fast & memory-efficient CUDA training\n",
            "                with torch.cuda.amp.autocast(enabled=torch.cuda.is_available()):\n",
            "                    output = model(input_ids, attention_mask, labels=labels, class_weights=class_weights)\n",
            "                    loss = output[\"loss\"] / grad_accum\n",
            "\n",
            "                scaler.scale(loss).backward()\n",
            "\n",
            "                if (step + 1) % grad_accum == 0 or (step + 1) == len(train_loader):\n",
            "                    scaler.step(optimizer)\n",
            "                    scaler.update()\n",
            "                    scheduler.step()\n",
            "                    optimizer.zero_grad()\n",
            "\n",
            "                total_train_loss += loss.item() * grad_accum\n",
            "\n",
            "            avg_train_loss = total_train_loss / len(train_loader)\n",
            "\n",
            "            # Evaluate Val F1 & Loss for EVERY epoch\n",
            "            model.eval()\n",
            "            y_true_epoch = {asp: [] for asp in ASPECTS}\n",
            "            y_pred_epoch = {asp: [] for asp in ASPECTS}\n",
            "\n",
            "            with torch.no_grad():\n",
            "                for batch in val_loader:\n",
            "                    input_ids = batch[\"input_ids\"].to(device)\n",
            "                    attention_mask = batch[\"attention_mask\"].to(device)\n",
            "                    labels = batch[\"labels\"]\n",
            "\n",
            "                    with torch.cuda.amp.autocast(enabled=torch.cuda.is_available()):\n",
            "                        output = model(input_ids, attention_mask)\n",
            "                    logits = output[\"logits\"]\n",
            "\n",
            "                    for asp in ASPECTS:\n",
            "                        preds = predict_with_threshold(logits[asp], aspect=asp)\n",
            "                        y_pred_epoch[asp].extend(preds)\n",
            "                        y_true_epoch[asp].extend(labels[asp].numpy())\n",
            "\n",
            "            epoch_eval = evaluate_predictions(y_true_epoch, y_pred_epoch)\n",
            "            val_f1_act = epoch_eval[\"overall\"][\"mean_macro_f1_active\"]\n",
            "            val_f1_all = epoch_eval[\"overall\"][\"mean_macro_f1_all\"]\n",
            "            val_acc = epoch_eval[\"overall\"][\"mean_accuracy\"]\n",
            "\n",
            "            # Real-Time Logging per Epoch\n",
            "            print(f\"  Epoch {epoch:2d}/{epochs} | Train Loss: {avg_train_loss:.4f} | Val F1 (Active): {val_f1_act:.4f} | Val F1 (All): {val_f1_all:.4f} | Val Acc: {val_acc:.4f}\")\n",
            "\n",
            "            if val_f1_act > best_fold_f1_active:\n",
            "                best_fold_f1_active = val_f1_act\n",
            "                best_fold_eval = epoch_eval\n",
            "\n",
            "            # Save single best model across ALL 5 folds\n",
            "            if val_f1_act > best_overall_val_f1:\n",
            "                best_overall_val_f1 = val_f1_act\n",
            "                torch.save(model.state_dict(), best_model_path)\n",
            "                print(f\"  🌟 MODEL TERBAIK BARU DISIMPAN! (Val F1 Active: {val_f1_act:.4f})\")\n",
            "\n",
            "        print(f\"⭐ Fold {fold} Best Val F1 (Active): {best_fold_f1_active:.4f}\")\n",
            "        fold_metrics.append(best_fold_eval)\n",
            "\n",
            "        # Memory Cleanup per fold\n",
            "        del model, optimizer, scheduler\n",
            "        gc.collect()\n",
            "        if torch.cuda.is_available():\n",
            "            torch.cuda.empty_cache()\n",
            "\n",
            "    tokenizer.save_pretrained(save_dir)\n",
            "    print(f\"\\n🏆 SELESAI: 5-Fold Cross Validation XLM-RoBERTa Selesai!\")\n",
            "    print(f\"💾 Single Best Model Tersimpan di: {best_model_path.resolve()} (Best Val F1 Active: {best_overall_val_f1:.4f})\")\n",
            "    return fold_metrics\n"
        ]
    },
    # CELL 13: Section 7 Markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 7. Eksekusi Pelatihan XLM-RoBERTa Lokal (5-Fold Stratified CV)\n"
        ]
    },
    # CELL 14: Section 7 Code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Pilihan model XLM-RoBERTa:\n",
            "# - 'xlm-roberta-base' (270M params - Direkomendasikan untuk GPU VRAM 4GB seperti RTX 3050)\n",
            "# - 'xlm-roberta-large' (550M params - Untuk GPU VRAM 8GB+)\n",
            "\n",
            "xlm_model_name = \"xlm-roberta-base\"\n",
            "print(f\"📦 Mengunduh & Memuat Tokenizer: {xlm_model_name}...\")\n",
            "xlm_tokenizer = AutoTokenizer.from_pretrained(xlm_model_name)\n",
            "\n",
            "# Konfigurasi pelatihan lokal:\n",
            "# Epochs: 20\n",
            "# Learning Rate: 2e-5\n",
            "# Batch Size: 16 (atau 8 jika VRAM terbatas)\n",
            "xlm_fold_metrics = train_5fold_cv_local(\n",
            "    model_name=xlm_model_name,\n",
            "    tokenizer=xlm_tokenizer,\n",
            "    full_df=full_df,\n",
            "    epochs=20,\n",
            "    lr=2e-5,\n",
            "    batch_size=16,\n",
            "    grad_accum=1,\n",
            "    save_prefix=\"xlmroberta_local_absa\",\n",
            "    unfreeze_last_n_layers=None  # Set misal 4 jika ingin partial fine-tuning\n",
            ")\n",
            "\n",
            "xlm_f1_active_folds = [m[\"overall\"][\"mean_macro_f1_active\"] for m in xlm_fold_metrics]\n",
            "xlm_f1_all_folds = [m[\"overall\"][\"mean_macro_f1_all\"] for m in xlm_fold_metrics]\n",
            "xlm_acc_folds = [m[\"overall\"][\"mean_accuracy\"] for m in xlm_fold_metrics]\n",
            "\n",
            "print(\"\\n📊 HASIL EVALUASI LOKAL 5-FOLD CV — XLM-ROBERTA:\")\n",
            "print(f\"  • Mean Macro F1 (Active Sentiments): {np.mean(xlm_f1_active_folds):.4f} ± {np.std(xlm_f1_active_folds):.4f}\")\n",
            "print(f\"  • Mean Macro F1 (All Classes)      : {np.mean(xlm_f1_all_folds):.4f} ± {np.std(xlm_f1_all_folds):.4f}\")\n",
            "print(f\"  • Mean Accuracy                  : {np.mean(xlm_acc_folds):.4f} ± {np.std(xlm_acc_folds):.4f}\")\n"
        ]
    },
    # CELL 15: Section 8 Markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 8. Export Metrics & Visualisasi Confusion Matrix\n"
        ]
    },
    # CELL 16: Section 8 Code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Simpan Ringkasan Metrik\n",
            "summary_df = pd.DataFrame([{\n",
            "    \"Model\": f\"{xlm_model_name} Classifier\",\n",
            "    \"Mean Macro F1 (Active)\": f\"{np.mean(xlm_f1_active_folds):.4f} ± {np.std(xlm_f1_active_folds):.4f}\",\n",
            "    \"Mean Macro F1 (All)\": f\"{np.mean(xlm_f1_all_folds):.4f} ± {np.std(xlm_f1_all_folds):.4f}\",\n",
            "    \"Mean Accuracy\": f\"{np.mean(xlm_acc_folds):.4f} ± {np.std(xlm_acc_folds):.4f}\",\n",
            "}])\n",
            "\n",
            "display(summary_df)\n",
            "summary_df.to_csv(\"xlmroberta_local_metrics_5fold.csv\", index=False)\n",
            "\n",
            "# Visualisasi Confusion Matrix Fold Terakhir\n",
            "last_cm = xlm_fold_metrics[-1][\"confusion_matrices\"]\n",
            "plot_confusion_matrices(last_cm, f\"{xlm_model_name} Local\", \"xlmroberta_local_confusion_matrices.png\")\n",
            "\n",
            "print(\"✅ Metrik & Confusion Matrix berhasil disimpan ke folder lokal!\")\n"
        ]
    }
]

notebook = {
    "cells": cells,
    "metadata": {
        "language_info": {"name": "python"}
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

target_file = "notebooks/04_local_training_xlmroberta.ipynb"
with open(target_file, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print(f"Created notebook {target_file} successfully!")
