[theme]
base = "dark"
primaryColor = "#2a5298"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
maxUploadSize = 200
